# This is a basic workflow to help you get started with Actions
name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Build with MPLAB X and XC8
        uses: nahueespinosa/ghactions-mplabx-xc8@b66f29d13a78083f9406b91d847bf04d00f41f9f
        with:
          project: .
          configuration: default
